apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080